import Dashboard from './Dashboard';
import Home from './Home';
import Login from './Login';
import NotFound from './NotFound';
import AllNotifications from './AllNotifications';
import SignUp from './SignUp';
import SinglePost from './SinglePost';
import UserProfile from './UserProfile';
import Loading from './Loading';

export { Dashboard };
export { Home };
export { Login };
export { NotFound };
export { AllNotifications };
export { SignUp };
export { SinglePost };
export { UserProfile };
export { Loading };
